### ISSUE TITLE
i2pd package build fails

### ISSUE THREAD

**Issue by l-n-s** [chantisnake/chocolateyPackage#1]
https://chocolatey.org/packages/i2pd/2.12.0 seems to fail at checksums stage

**Comment by czhang03** [comment]
hum. I will check that out. Thank your for your report

**Comment by czhang03** [comment]
also can you try to update to latest version of choco?

**Comment by l-n-s** [comment]
I don't have any Windows machines right now, so can't help

**Comment by czhang03** [comment]
I finally understood what you mean...
I am kind of busy recently... I will fix it now.

**Comment by czhang03** [comment]
it passes the checksum
