### ISSUE TITLE
Rocket.chat 2.8.0 has been release

### ISSUE THREAD

**Issue by cmorty** [chantisnake/chocolateyPackage#3]
https://github.com/RocketChat/Rocket.Chat.Electron/releases/ - The still link the old version on their website

**Comment by czhang03** [comment]
I am currently in mainland China. Because of network issue my updater cannot work.

I will update all my packages when I get back to U.S. Thank you for your feed back, I will tell you when the new version got pushed

**Comment by czhang03** [comment]
pushed and approved
