### ISSUE TITLE
Anaconda 5.0.0 has been released

### ISSUE THREAD

**Issue by radzio** [chantisnake/chocolateyPackage#4]
Anaconda 5.0.0 was released: https://repo.continuum.io/archive/Anaconda3-5.0.0-Windows-x86_64.exe

**Comment by czhang03** [comment]
I will update this in these days. Thanks!

**Comment by radzio** [comment]
👌

**Comment by czhang03** [comment]
Both packages are pushed and `anaconda3` is already approved.

Thank you again for your issue. Please feel free to post it again if I forget to update in the future.

Best,
Cheng

**Comment by radzio** [comment]
Thanks!
