### ISSUE TITLE
DNSCrypt Update

### ISSUE THREAD

**Issue by zero77** [chantisnake/chocolateyPackage#6]
There is a new version of DNSCrypt out on github also, they now support x64.
https://github.com/bitbeans/SimpleDnsCrypt/releases

**Comment by czhang03** [comment]
Latest version is updated and pushed!

Thank you for your issue. Please feel free to post further issue if any other package is not updated or there is a new 64 bits or 32 bits version.

Thanks

**Comment by zero77** [comment]
Thanks, although could you get it to automatically update as it may make things easier.

**Comment by czhang03** [comment]
I have an update script, but unfortunately I don't have an update server.

I just run it myself every other week (If I can actually remember.)
