### ISSUE TITLE
大佬，这个该怎么用呀？

### ISSUE THREAD

**Issue by LunaFlow** [chantisnake/chocolateyPackage#7]

**Comment by czhang03** [comment]
这个并不是用的，这个是我 manage 的 chocolatey package，你如果需要这些软件可以用 chocolatey 安装。

https://chocolatey.org/

**Comment by LunaFlow** [comment]
我用过chocolatey 下载过一些软件。一般choco install + 软件名就下载了。有些好奇，你这些配置是用来做什么的。

**Comment by czhang03** [comment]
@LunaFlow 谢谢你关心这个 repo。

chocolatey 的原理是 package maintainer（维护者）来上传有关于软件的信息（比如 hash，下载地址，如何安装，官网之类的信息）到 chocolatey server 上面。
这样用户每次安装的时候就下载相关的文件，执行指定的操作。

这个 repo 里面放的就是我维护的所有 package。

具体有关维护 chocolatey package 的文档可以看这里：https://chocolatey.org/docs/create-packages
