### ISSUE TITLE
SimpleDnsCrypt Update

### ISSUE THREAD

**Issue by zero77** [chantisnake/chocolateyPackage#8]
SimpleDnsCrypt 0.4.5 is now out, can you please update the chocolatey Package.
Thanks

**Comment by czhang03** [comment]
A new package is pushed.
 because recently they changed the installer type (from `zip` to `msi`), I am not sure how well the package works. 
Please test. Thank you.

**Comment by zero77** [comment]
ok, thanks.

**Comment by zero77** [comment]
The developer seems to be very fast and 0.4.6 is now out and there may be more soon.

https://github.com/bitbeans/SimpleDnsCrypt/releases

**Comment by czhang03** [comment]
Uhhh. 0.4.5 still haven't passed the automated testing. It works on my machine but always fail with exit code 1603 on the automated testing environment.

Hopefully this version will not have this issue. Thank you.
